apiversion: apps/v1
kind: Deployment
metadata:
  name: myapp:v1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp:v1
  template:
    metadata:
      lables:
        app: myapp:v1
    spec:
      containers:
        - name: myapp:v1
          image: kadarinandhini/sample:t1 
          ports:
            - containerPort: 5000
