apiversion: v1
kind: Service
metadata:
  name: myapp:v1-service
spec:
  selector:
    app: myapp:v1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
  type: nodePort
